services:
  haproxy:
    image: haproxy-dns
    depends_on:
    - nginx_a
    - nginx_b
    - nginx_c
    ports:
    - "8081:8081"
    - "8082:8082"
    - "8083:8083"
    - "1936:1936"
    environment:

      FRONTEND_POOLS: 3
      FRONTEND1_PORT: "8081"
      FRONTEND2_PORT: "8082"
      FRONTEND3_PORT: "8083"

      BACKEND_PORT: "80"
      BACKEND1_HOST: "nginx_a"
      BACKEND1_DEFAULT_SERVER: "inter 2s fastinter 2s downinter 2s fall 3 rise 2 minconn 50 maxconn 100 pool-low-conn 5 pool-max-conn 10"
      BACKEND2_HOST: "nginx_b"
      BACKEND2_BALANCE: "first"
      BACKEND3_HOST: "nginx_c"

      HTTPCHK: "GET /"
      LOG_LEVEL: "info"

  nginx_a:
    image: nginx
    ports:
      - 80

  nginx_b:
    image: nginx
    ports:
      - 80

  nginx_c:
    image: nginx
    ports:
      - 80
